### ISSUE TITLE
Enable printing Unicode characters to output

### ISSUE THREAD

**Issue by jstallent** [titusz/onixcheck#1]
Thanks for this great tool! I was running the validator on some ONIX files and ran into an issue where a zero-width space had gotten into my code because of copy/paste. When running the script, I was getting a Python error:

Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\onixcheck.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\onixcheck\__main__.py", line 80, in main
    print(msg.short, file=sys.stderr)
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u200b' in position 103: character maps to <undefined>

After a bit of digging I saw that all I needed to do was change line 80 in __main__.py from:
print(msg.short, file=sys.stderr)
to
print(msg.short.encode("utf-8"), file=sys.stderr)

This instead gives the following error messages, which allowed me to find the characters and eliminate them. 

ERROR - SCHEMASV - test.xml:91:0 - Element 'NameIDType': [facet 'enumeration'] The value '16ΓÇï' is not an element of the set .
ERROR - SCHEMASV - test.xml:91:0 - Element 'NameIDType': '16ΓÇï' is not a valid value of the atomic type 'List44'.

**Comment by titusz** [comment]
Thanks for reporting the issue. Python and the windows console are not the best friends (see https://github.com/Drekin/win-unicode-console). I am not sure if it is a good idea to do a hardcoded 'utf8' encoding before sending to sys.stderr. Could you send me a failing test.xml onix, so I can try reproduce the error and check how to fix this in a generic way.

**Comment by jstallent** [comment]
Here you go. I made sure everything else validates so only the Unicode issue is present. Changed the extension to .txt so it would upload here. 
[UnicodeError.txt](https://github.com/titusz/onixcheck/files/350554/UnicodeError.txt)

**Comment by titusz** [comment]
Thank you for providing the example. I have just released a new version (0.9.4) that should fix this issue. Let me know if it works...
